#!/bin/bash

echo "======================================"
echo "Price Sticker Printer - Web App Setup"
echo "======================================"
echo ""
echo "To run the web application, you need to:"
echo ""
echo "1. Install Python pip (if not already installed):"
echo "   Ubuntu/Debian: sudo apt-get install python3-pip python3-venv"
echo "   macOS: brew install python3"
echo "   Windows: pip should come with Python installation"
echo ""
echo "2. Create a virtual environment (recommended):"
echo "   python3 -m venv venv"
echo "   source venv/bin/activate  # On Windows: venv\\Scripts\\activate"
echo ""
echo "3. Install dependencies:"
echo "   pip install -r requirements.txt"
echo ""
echo "4. Run the application:"
echo "   python app.py"
echo ""
echo "5. Open your browser to:"
echo "   http://localhost:5000"
echo ""
echo "======================================"